/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.developer.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TrackPurchase extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5718620818668704674L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TrackPurchase\",\"namespace\":\"io.confluent.developer.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"song_title\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"album_id\",\"type\":\"long\"},{\"name\":\"price\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TrackPurchase> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TrackPurchase> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TrackPurchase> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TrackPurchase> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TrackPurchase> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TrackPurchase to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TrackPurchase from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TrackPurchase instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TrackPurchase fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long id;
  private java.lang.String song_title;
  private long album_id;
  private double price;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TrackPurchase() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param song_title The new value for song_title
   * @param album_id The new value for album_id
   * @param price The new value for price
   */
  public TrackPurchase(java.lang.Long id, java.lang.String song_title, java.lang.Long album_id, java.lang.Double price) {
    this.id = id;
    this.song_title = song_title;
    this.album_id = album_id;
    this.price = price;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return song_title;
    case 2: return album_id;
    case 3: return price;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: song_title = value$ != null ? value$.toString() : null; break;
    case 2: album_id = (java.lang.Long)value$; break;
    case 3: price = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }



  /**
   * Gets the value of the 'song_title' field.
   * @return The value of the 'song_title' field.
   */
  public java.lang.String getSongTitle() {
    return song_title;
  }



  /**
   * Gets the value of the 'album_id' field.
   * @return The value of the 'album_id' field.
   */
  public long getAlbumId() {
    return album_id;
  }



  /**
   * Gets the value of the 'price' field.
   * @return The value of the 'price' field.
   */
  public double getPrice() {
    return price;
  }



  /**
   * Creates a new TrackPurchase RecordBuilder.
   * @return A new TrackPurchase RecordBuilder
   */
  public static io.confluent.developer.avro.TrackPurchase.Builder newBuilder() {
    return new io.confluent.developer.avro.TrackPurchase.Builder();
  }

  /**
   * Creates a new TrackPurchase RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TrackPurchase RecordBuilder
   */
  public static io.confluent.developer.avro.TrackPurchase.Builder newBuilder(io.confluent.developer.avro.TrackPurchase.Builder other) {
    if (other == null) {
      return new io.confluent.developer.avro.TrackPurchase.Builder();
    } else {
      return new io.confluent.developer.avro.TrackPurchase.Builder(other);
    }
  }

  /**
   * Creates a new TrackPurchase RecordBuilder by copying an existing TrackPurchase instance.
   * @param other The existing instance to copy.
   * @return A new TrackPurchase RecordBuilder
   */
  public static io.confluent.developer.avro.TrackPurchase.Builder newBuilder(io.confluent.developer.avro.TrackPurchase other) {
    if (other == null) {
      return new io.confluent.developer.avro.TrackPurchase.Builder();
    } else {
      return new io.confluent.developer.avro.TrackPurchase.Builder(other);
    }
  }

  /**
   * RecordBuilder for TrackPurchase instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TrackPurchase>
    implements org.apache.avro.data.RecordBuilder<TrackPurchase> {

    private long id;
    private java.lang.String song_title;
    private long album_id;
    private double price;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.confluent.developer.avro.TrackPurchase.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.song_title)) {
        this.song_title = data().deepCopy(fields()[1].schema(), other.song_title);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.album_id)) {
        this.album_id = data().deepCopy(fields()[2].schema(), other.album_id);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.price)) {
        this.price = data().deepCopy(fields()[3].schema(), other.price);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing TrackPurchase instance
     * @param other The existing instance to copy.
     */
    private Builder(io.confluent.developer.avro.TrackPurchase other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.song_title)) {
        this.song_title = data().deepCopy(fields()[1].schema(), other.song_title);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.album_id)) {
        this.album_id = data().deepCopy(fields()[2].schema(), other.album_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.price)) {
        this.price = data().deepCopy(fields()[3].schema(), other.price);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public io.confluent.developer.avro.TrackPurchase.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public io.confluent.developer.avro.TrackPurchase.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'song_title' field.
      * @return The value.
      */
    public java.lang.String getSongTitle() {
      return song_title;
    }


    /**
      * Sets the value of the 'song_title' field.
      * @param value The value of 'song_title'.
      * @return This builder.
      */
    public io.confluent.developer.avro.TrackPurchase.Builder setSongTitle(java.lang.String value) {
      validate(fields()[1], value);
      this.song_title = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'song_title' field has been set.
      * @return True if the 'song_title' field has been set, false otherwise.
      */
    public boolean hasSongTitle() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'song_title' field.
      * @return This builder.
      */
    public io.confluent.developer.avro.TrackPurchase.Builder clearSongTitle() {
      song_title = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'album_id' field.
      * @return The value.
      */
    public long getAlbumId() {
      return album_id;
    }


    /**
      * Sets the value of the 'album_id' field.
      * @param value The value of 'album_id'.
      * @return This builder.
      */
    public io.confluent.developer.avro.TrackPurchase.Builder setAlbumId(long value) {
      validate(fields()[2], value);
      this.album_id = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'album_id' field has been set.
      * @return True if the 'album_id' field has been set, false otherwise.
      */
    public boolean hasAlbumId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'album_id' field.
      * @return This builder.
      */
    public io.confluent.developer.avro.TrackPurchase.Builder clearAlbumId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'price' field.
      * @return The value.
      */
    public double getPrice() {
      return price;
    }


    /**
      * Sets the value of the 'price' field.
      * @param value The value of 'price'.
      * @return This builder.
      */
    public io.confluent.developer.avro.TrackPurchase.Builder setPrice(double value) {
      validate(fields()[3], value);
      this.price = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'price' field has been set.
      * @return True if the 'price' field has been set, false otherwise.
      */
    public boolean hasPrice() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'price' field.
      * @return This builder.
      */
    public io.confluent.developer.avro.TrackPurchase.Builder clearPrice() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TrackPurchase build() {
      try {
        TrackPurchase record = new TrackPurchase();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.song_title = fieldSetFlags()[1] ? this.song_title : (java.lang.String) defaultValue(fields()[1]);
        record.album_id = fieldSetFlags()[2] ? this.album_id : (java.lang.Long) defaultValue(fields()[2]);
        record.price = fieldSetFlags()[3] ? this.price : (java.lang.Double) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TrackPurchase>
    WRITER$ = (org.apache.avro.io.DatumWriter<TrackPurchase>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TrackPurchase>
    READER$ = (org.apache.avro.io.DatumReader<TrackPurchase>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.id);

    out.writeString(this.song_title);

    out.writeLong(this.album_id);

    out.writeDouble(this.price);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      this.song_title = in.readString();

      this.album_id = in.readLong();

      this.price = in.readDouble();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readLong();
          break;

        case 1:
          this.song_title = in.readString();
          break;

        case 2:
          this.album_id = in.readLong();
          break;

        case 3:
          this.price = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










