/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gmail.pzalejko.cdc;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AccountAggregateKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5839711861053099588L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AccountAggregateKey\",\"namespace\":\"com.gmail.pzalejko.cdc\",\"fields\":[{\"name\":\"account_owner_id\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AccountAggregateKey> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AccountAggregateKey> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AccountAggregateKey> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AccountAggregateKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AccountAggregateKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AccountAggregateKey to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AccountAggregateKey from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AccountAggregateKey instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AccountAggregateKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long account_owner_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AccountAggregateKey() {}

  /**
   * All-args constructor.
   * @param account_owner_id The new value for account_owner_id
   */
  public AccountAggregateKey(java.lang.Long account_owner_id) {
    this.account_owner_id = account_owner_id;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return account_owner_id;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: account_owner_id = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'account_owner_id' field.
   * @return The value of the 'account_owner_id' field.
   */
  public long getAccountOwnerId() {
    return account_owner_id;
  }



  /**
   * Creates a new AccountAggregateKey RecordBuilder.
   * @return A new AccountAggregateKey RecordBuilder
   */
  public static com.gmail.pzalejko.cdc.AccountAggregateKey.Builder newBuilder() {
    return new com.gmail.pzalejko.cdc.AccountAggregateKey.Builder();
  }

  /**
   * Creates a new AccountAggregateKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AccountAggregateKey RecordBuilder
   */
  public static com.gmail.pzalejko.cdc.AccountAggregateKey.Builder newBuilder(com.gmail.pzalejko.cdc.AccountAggregateKey.Builder other) {
    if (other == null) {
      return new com.gmail.pzalejko.cdc.AccountAggregateKey.Builder();
    } else {
      return new com.gmail.pzalejko.cdc.AccountAggregateKey.Builder(other);
    }
  }

  /**
   * Creates a new AccountAggregateKey RecordBuilder by copying an existing AccountAggregateKey instance.
   * @param other The existing instance to copy.
   * @return A new AccountAggregateKey RecordBuilder
   */
  public static com.gmail.pzalejko.cdc.AccountAggregateKey.Builder newBuilder(com.gmail.pzalejko.cdc.AccountAggregateKey other) {
    if (other == null) {
      return new com.gmail.pzalejko.cdc.AccountAggregateKey.Builder();
    } else {
      return new com.gmail.pzalejko.cdc.AccountAggregateKey.Builder(other);
    }
  }

  /**
   * RecordBuilder for AccountAggregateKey instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AccountAggregateKey>
    implements org.apache.avro.data.RecordBuilder<AccountAggregateKey> {

    private long account_owner_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.gmail.pzalejko.cdc.AccountAggregateKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.account_owner_id)) {
        this.account_owner_id = data().deepCopy(fields()[0].schema(), other.account_owner_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing AccountAggregateKey instance
     * @param other The existing instance to copy.
     */
    private Builder(com.gmail.pzalejko.cdc.AccountAggregateKey other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.account_owner_id)) {
        this.account_owner_id = data().deepCopy(fields()[0].schema(), other.account_owner_id);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'account_owner_id' field.
      * @return The value.
      */
    public long getAccountOwnerId() {
      return account_owner_id;
    }


    /**
      * Sets the value of the 'account_owner_id' field.
      * @param value The value of 'account_owner_id'.
      * @return This builder.
      */
    public com.gmail.pzalejko.cdc.AccountAggregateKey.Builder setAccountOwnerId(long value) {
      validate(fields()[0], value);
      this.account_owner_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'account_owner_id' field has been set.
      * @return True if the 'account_owner_id' field has been set, false otherwise.
      */
    public boolean hasAccountOwnerId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'account_owner_id' field.
      * @return This builder.
      */
    public com.gmail.pzalejko.cdc.AccountAggregateKey.Builder clearAccountOwnerId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AccountAggregateKey build() {
      try {
        AccountAggregateKey record = new AccountAggregateKey();
        record.account_owner_id = fieldSetFlags()[0] ? this.account_owner_id : (java.lang.Long) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AccountAggregateKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<AccountAggregateKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AccountAggregateKey>
    READER$ = (org.apache.avro.io.DatumReader<AccountAggregateKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.account_owner_id);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.account_owner_id = in.readLong();

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.account_owner_id = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










