/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gmail.pzalejko.cdc;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AccountAggregate extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8593331230317460007L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AccountAggregate\",\"namespace\":\"com.gmail.pzalejko.cdc\",\"fields\":[{\"name\":\"account_owner_id\",\"type\":\"long\"},{\"name\":\"account_id\",\"type\":\"long\"},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"balance\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AccountAggregate> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AccountAggregate> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AccountAggregate> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AccountAggregate> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AccountAggregate> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AccountAggregate to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AccountAggregate from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AccountAggregate instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AccountAggregate fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long account_owner_id;
  private long account_id;
  private java.lang.String name;
  private double balance;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AccountAggregate() {}

  /**
   * All-args constructor.
   * @param account_owner_id The new value for account_owner_id
   * @param account_id The new value for account_id
   * @param name The new value for name
   * @param balance The new value for balance
   */
  public AccountAggregate(java.lang.Long account_owner_id, java.lang.Long account_id, java.lang.String name, java.lang.Double balance) {
    this.account_owner_id = account_owner_id;
    this.account_id = account_id;
    this.name = name;
    this.balance = balance;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return account_owner_id;
    case 1: return account_id;
    case 2: return name;
    case 3: return balance;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: account_owner_id = (java.lang.Long)value$; break;
    case 1: account_id = (java.lang.Long)value$; break;
    case 2: name = value$ != null ? value$.toString() : null; break;
    case 3: balance = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'account_owner_id' field.
   * @return The value of the 'account_owner_id' field.
   */
  public long getAccountOwnerId() {
    return account_owner_id;
  }



  /**
   * Gets the value of the 'account_id' field.
   * @return The value of the 'account_id' field.
   */
  public long getAccountId() {
    return account_id;
  }



  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }



  /**
   * Gets the value of the 'balance' field.
   * @return The value of the 'balance' field.
   */
  public double getBalance() {
    return balance;
  }



  /**
   * Creates a new AccountAggregate RecordBuilder.
   * @return A new AccountAggregate RecordBuilder
   */
  public static com.gmail.pzalejko.cdc.AccountAggregate.Builder newBuilder() {
    return new com.gmail.pzalejko.cdc.AccountAggregate.Builder();
  }

  /**
   * Creates a new AccountAggregate RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AccountAggregate RecordBuilder
   */
  public static com.gmail.pzalejko.cdc.AccountAggregate.Builder newBuilder(com.gmail.pzalejko.cdc.AccountAggregate.Builder other) {
    if (other == null) {
      return new com.gmail.pzalejko.cdc.AccountAggregate.Builder();
    } else {
      return new com.gmail.pzalejko.cdc.AccountAggregate.Builder(other);
    }
  }

  /**
   * Creates a new AccountAggregate RecordBuilder by copying an existing AccountAggregate instance.
   * @param other The existing instance to copy.
   * @return A new AccountAggregate RecordBuilder
   */
  public static com.gmail.pzalejko.cdc.AccountAggregate.Builder newBuilder(com.gmail.pzalejko.cdc.AccountAggregate other) {
    if (other == null) {
      return new com.gmail.pzalejko.cdc.AccountAggregate.Builder();
    } else {
      return new com.gmail.pzalejko.cdc.AccountAggregate.Builder(other);
    }
  }

  /**
   * RecordBuilder for AccountAggregate instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AccountAggregate>
    implements org.apache.avro.data.RecordBuilder<AccountAggregate> {

    private long account_owner_id;
    private long account_id;
    private java.lang.String name;
    private double balance;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.gmail.pzalejko.cdc.AccountAggregate.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.account_owner_id)) {
        this.account_owner_id = data().deepCopy(fields()[0].schema(), other.account_owner_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.account_id)) {
        this.account_id = data().deepCopy(fields()[1].schema(), other.account_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.balance)) {
        this.balance = data().deepCopy(fields()[3].schema(), other.balance);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing AccountAggregate instance
     * @param other The existing instance to copy.
     */
    private Builder(com.gmail.pzalejko.cdc.AccountAggregate other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.account_owner_id)) {
        this.account_owner_id = data().deepCopy(fields()[0].schema(), other.account_owner_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.account_id)) {
        this.account_id = data().deepCopy(fields()[1].schema(), other.account_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.balance)) {
        this.balance = data().deepCopy(fields()[3].schema(), other.balance);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'account_owner_id' field.
      * @return The value.
      */
    public long getAccountOwnerId() {
      return account_owner_id;
    }


    /**
      * Sets the value of the 'account_owner_id' field.
      * @param value The value of 'account_owner_id'.
      * @return This builder.
      */
    public com.gmail.pzalejko.cdc.AccountAggregate.Builder setAccountOwnerId(long value) {
      validate(fields()[0], value);
      this.account_owner_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'account_owner_id' field has been set.
      * @return True if the 'account_owner_id' field has been set, false otherwise.
      */
    public boolean hasAccountOwnerId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'account_owner_id' field.
      * @return This builder.
      */
    public com.gmail.pzalejko.cdc.AccountAggregate.Builder clearAccountOwnerId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'account_id' field.
      * @return The value.
      */
    public long getAccountId() {
      return account_id;
    }


    /**
      * Sets the value of the 'account_id' field.
      * @param value The value of 'account_id'.
      * @return This builder.
      */
    public com.gmail.pzalejko.cdc.AccountAggregate.Builder setAccountId(long value) {
      validate(fields()[1], value);
      this.account_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'account_id' field has been set.
      * @return True if the 'account_id' field has been set, false otherwise.
      */
    public boolean hasAccountId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'account_id' field.
      * @return This builder.
      */
    public com.gmail.pzalejko.cdc.AccountAggregate.Builder clearAccountId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.gmail.pzalejko.cdc.AccountAggregate.Builder setName(java.lang.String value) {
      validate(fields()[2], value);
      this.name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.gmail.pzalejko.cdc.AccountAggregate.Builder clearName() {
      name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'balance' field.
      * @return The value.
      */
    public double getBalance() {
      return balance;
    }


    /**
      * Sets the value of the 'balance' field.
      * @param value The value of 'balance'.
      * @return This builder.
      */
    public com.gmail.pzalejko.cdc.AccountAggregate.Builder setBalance(double value) {
      validate(fields()[3], value);
      this.balance = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'balance' field has been set.
      * @return True if the 'balance' field has been set, false otherwise.
      */
    public boolean hasBalance() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'balance' field.
      * @return This builder.
      */
    public com.gmail.pzalejko.cdc.AccountAggregate.Builder clearBalance() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AccountAggregate build() {
      try {
        AccountAggregate record = new AccountAggregate();
        record.account_owner_id = fieldSetFlags()[0] ? this.account_owner_id : (java.lang.Long) defaultValue(fields()[0]);
        record.account_id = fieldSetFlags()[1] ? this.account_id : (java.lang.Long) defaultValue(fields()[1]);
        record.name = fieldSetFlags()[2] ? this.name : (java.lang.String) defaultValue(fields()[2]);
        record.balance = fieldSetFlags()[3] ? this.balance : (java.lang.Double) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AccountAggregate>
    WRITER$ = (org.apache.avro.io.DatumWriter<AccountAggregate>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AccountAggregate>
    READER$ = (org.apache.avro.io.DatumReader<AccountAggregate>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.account_owner_id);

    out.writeLong(this.account_id);

    out.writeString(this.name);

    out.writeDouble(this.balance);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.account_owner_id = in.readLong();

      this.account_id = in.readLong();

      this.name = in.readString();

      this.balance = in.readDouble();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.account_owner_id = in.readLong();
          break;

        case 1:
          this.account_id = in.readLong();
          break;

        case 2:
          this.name = in.readString();
          break;

        case 3:
          this.balance = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










