spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: tx-
      properties:
        enable.idempotence: true
        transactional.id: tran-id-1
  sql.init.mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db
    username: demo
    password: demo
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: validate #create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect