#
# launch back-end with the 'tx' profile
#
POST http://localhost:8080/accounts
Content-Type: application/json

{
  "name": "Jack",
  "surname": "Sparrow",
  "initBalance": 5000
}

###

POST http://localhost:8080/accounts
Content-Type: application/json

{
  "name": "Hector",
  "surname": "Barbossa",
  "initBalance": 3000
}

###
